### ISSUE TITLE
Serialize result to JSON

### ISSUE THREAD

**Issue by aeri** [zazuko/sparql-http-client#17]
I can't serialize the result of a query to JSON, i tried with the built in parser but it returns an error. The result may be a stream but i don't know how to convert to JSON.

Any help?

**Comment by tpluscode** [comment]
You are using the latest version, right?

**Comment by tpluscode** [comment]
Oh, I see now that the readme is outdated, while we have not yet built the documentation pages we wanted. Sorry about that.

If you don't care about stream processing you can use the `ParsingClient` which return a fully materialised RDF/JS `Dataset` or an array of bindings in the case of SELECT

```js
const ParsingClient = require('sparql-http-client/ParsingClient')

const client = new ParsingClient({
  endpointUrl: 'https://dbpedia.org/sparql'
})

const bindings = await client.query.select(`SELECT * WHERE { ?s ?p ?o } LIMIT 2`)

bindings.map(result => ({
 s: result.s.value,
 p: result.p.value,
 o: result.o.value
}))
```

Note that the bindings return RDF/JS Terms, hence the simple `map` to get their plain string values

**Comment by aeri** [comment]
Thank you for quickly support, the solution works perfectly, I wasn't using `ParsingClient,` only `SparqlClient`, now with the mapping I can get the JSON I want.
