### ISSUE TITLE
Is there any capability to get all the returned variables (header)

### ISSUE THREAD

**Issue by CoryCasanave** [zazuko/sparql-http-client#19]
To make a nice table from generic query results you need to know what may come back. Is there any facility for getting all the possible return variables?
e.g. "Select * {?Person a :Person, optional {?Person :hasName ?Name}}"

Would return ["Person", "Name"]

**Comment by tpluscode** [comment]
If your query is a string you cannot get the variable names up front. This library does not parse them.

You will only be able to find the variable names once the query has been executed.

Otherwise you might turn to [sparqljs](https://www.npmjs.com/package/sparqljs)

**Comment by tpluscode** [comment]
We have just published documentation pages we had been working on https://zazuko.github.io/sparql-http-client

The examples there should help you achieve what I outlined above
