### ISSUE TITLE
How to use in typescript?

### ISSUE THREAD

**Issue by mielvds** [zazuko/sparql-http-client#36]
Hi there!
Importing the library in typescript is giving me some trouble.
After adding `"@types/sparql-http-client": "^2.2.7",` to my package.json, I tried 

- `import * as StreamClient from "sparql-http-client";` --> This expression is not constructable.
- `import StreamClient from "sparql-http-client";` --> ERR_MODULE_NOT_FOUND
- `import {StreamClient} from ` --> 'StreamClient' only refers to a type, but is being used as a value here.

How can I make this work?
Alos, it seems the type definitions are not up to date, could that be?

**Comment by tpluscode** [comment]
Do you have `"esModuleInterop": true` in your tsconfig?

**Comment by mielvds** [comment]
I didn't, but adding it doesn't change anything.

**Comment by tpluscode** [comment]
Are you able to provide link to your code? Doesn't have to be a minimal repro for now

**Comment by mielvds** [comment]
I have some preliminary code here: https://github.com/viaacode/grasp/blob/rdfjs/resource.ts#L202

**Comment by tpluscode** [comment]
`import SparqlClient from "sparql-http-client"`

This works fine in your code, as it should. Try cleaning your repo and reinstalling node modules

**Comment by mielvds** [comment]
right, I was also missing the actual module `"sparql-http-client": "^2.4.0",` in my package.json. Thanks!
