### ISSUE TITLE
Connect to Endpoint

### ISSUE THREAD

**Issue by dabuchera** [zazuko/sparql-http-client#40]
Hi

Running into similar problems as [https://github.com/zazuko/sparql-http-client/issues/30](https://github.com/zazuko/sparql-http-client/issues/30)

The endpoint is a Fuseki Server running locally with the following dataset

```turtle
@prefix bot:      <https://w3id.org/bot#> .
@prefix bot_test: <http://example.org/bot_test#> .
@prefix cc:       <http://creativecommons.org/ns#> .
@prefix dbo:      <http://dbpedia.org/ontology/> .
@prefix dc:       <http://purl.org/dc/terms/> .
@prefix dce:      <http://purl.org/dc/elements/1.1/> .
@prefix owl:      <http://www.w3.org/2002/07/owl#> .
@prefix rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:     <http://www.w3.org/2000/01/rdf-schema#> .
@prefix vann:     <http://purl.org/vocab/vann/> .
@prefix xml:      <http://www.w3.org/XML/1998/namespace> .
@prefix xsd:      <http://www.w3.org/2001/XMLSchema#> .
<http://example.org/bot_test>
        rdf:type         owl:Ontology ;
        cc:license       <http://creativecommons.org/licenses/by/3.0/> ;
        dce:description  "Example showing how the BOT ontology can be used to describe the topology of a building.\nThe building has four external walls and consists of 2 storeys. In the first storey there are rooms 101 and 102. In the second storey there is room 201.\nRoom 101 has an entrance door, one window and a table.\nRoom 102 has a window and a sofa.\nA door connects room 101 and room 102.\nA trapdoor connects room 102 and room 201." ;
        dc:creator       <http://www.terkaj.com#walter> ;
        dc:issued        "2017-04-05"^^xsd:date ;
        dc:modified      "2017-04-05"^^xsd:date ;
        owl:imports      <https://w3id.org/bot> .
bot_test:BuildingTest
        rdf:type       owl:NamedIndividual , bot:Building ;
        bot:hasStorey  bot_test:Storey1 , bot_test:Storey2 .
bot_test:Storey1  rdf:type  owl:NamedIndividual , bot:Storey ;
        bot:hasSpace  bot_test:Room101 , bot_test:Room102 .
bot_test:Storey2  rdf:type  owl:NamedIndividual , bot:Storey ;
        bot:hasSpace  bot_test:Room201 .
bot_test:Room101  rdf:type   owl:NamedIndividual , bot:Space ;
        bot:adjacentElement  bot_test:door_101_102 , bot_test:door_entrance , bot_test:wall_101_102 , bot_test:wall_external_N , bot_test:wall_external_S , bot_test:wall_external_W , bot_test:window101 ;
        bot:containsElement  bot_test:table_101 .
```

Querying directly on fuseki works but getting following error

![image](https://user-images.githubusercontent.com/53481997/173156093-ff987158-47a0-4470-bbf0-adbe894901e1.png)

Tried out different clients such as StreamQuery, Parsing. The error above results with the SparqlClient (see below)

![image](https://user-images.githubusercontent.com/53481997/173156215-3ef80e78-254d-4b23-b310-df1c1d40e41e.png)

**Comment by dabuchera** [comment]
When running Queries with the SparqlClient such as the following, I'm running into errors like below

![image](https://user-images.githubusercontent.com/53481997/173157303-83c69947-6834-4a39-be32-2d9cce6bf225.png)

![image](https://user-images.githubusercontent.com/53481997/173157324-914ed53e-9313-4626-bd3f-1bc3423e48d2.png)

**Comment by tpluscode** [comment]
Judging by the error, the response you get is a HTML document. I guess. that might be the Fuseki's UI. 

Are you sure the the `endpointUrl` is correct? May be missing the `/query` in path

**Comment by dabuchera** [comment]
`endpointUrl` should be correct. Fuseki running on

 `http://localhost:3030/#/dataset/ds/query` 
or
 `http://localhost:3030/#/dataset/ds/sparql`

![image](https://user-images.githubusercontent.com/53481997/173194702-57a3d5d5-d29f-4b78-ac64-8ce66ead0092.png)

**Comment by dabuchera** [comment]
Not sure if it is maybe because of the Turtle syntax of the data

**Comment by dabuchera** [comment]
Ok Solved

The following mistake were done:

First, read the the SPARQL docs in detail -> [Link](https://www.w3.org/2009/sparql/docs/protocol-1.1/)
Three different possibilities are possible to query. All of them are possible and well documented in the types definition

![image](https://user-images.githubusercontent.com/53481997/173202331-a46f9226-a0a8-4f15-9303-8213d3288480.png)

![image](https://user-images.githubusercontent.com/53481997/173202334-02bb0851-bea6-4a38-8436-c74e34546208.png)

Second, Make sure the query is formatted right i.e. only as a string, and assure that the header has the right `Content-Type` set 

![image](https://user-images.githubusercontent.com/53481997/173202429-ce0ae29b-8827-4b3f-8439-9ac5b946b9a8.png)

**Comment by tpluscode** [comment]
> Fuseki running on
>
> http://localhost:3030/#/dataset/ds/query
> or
> http://localhost:3030/#/dataset/ds/sparql

Those are not Fuseki's SPARQL endpoints but the user interface. You should instead use `http://localhost:3030/ds/query`
